api-version: 1.16
author: tickleman
load: STARTUP
main: fr.crafter.tickleman.realplugin.RealPluginPlugin
name: RealPlugin
commands:
  realplugin:
    aliases: [rp]
    description: RealPlugin plugins manager
    usage: /rp help
  realrecipes:
    aliases: [rr]
    description: Information commands about recipes
    usage: /rr dump
  realtests:
    aliases: [rt]
    description: Run all tests
    usage: /rt
version: 1.7.11
website: http://plugins.crafter.fr/tickleman/RealPlugin/
