name: RealPlugin
main: fr.crafter.tickleman.realplugin.RealPluginPlugin
version: 1.7.10
website: http://plugins.crafter.fr/tickleman/RealPlugin/
author: tickleman
load: STARTUP
commands:
  realplugin:
    aliases: [rp]
    description: RealPlugin plugins manager
    usage: /rp help
  realrecipes:
    aliases: [rr]
    description: Information commands about recipes
    usage: /rr dump
  realtests:
    aliases: [rt]
    description: Run all tests
    usage: /rt